import Head from "next/head";
import Link from "next/link";

import styles from "../styles/Home.module.css";
import { Footer, SearchForm } from "../components";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <Link href="/">Hometown Hire</Link>
        </h1>
        <p className={styles.description}>Get started by searching a Hire</p>
        <SearchForm />
      </main>
      <Footer />
    </div>
  );
}
